# Generated by Django 5.2.8 on 2025-11-26 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todo_remove_task_category_remove_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='created_at',
            new_name='date',
        ),
    ]
