# Generated by Django 5.2.8 on 2025-11-26 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_rename_description_todo_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='details',
            new_name='description',
        ),
    ]
