# Generated by Django 5.2.8 on 2025-11-26 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_rename_details_todo_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='date',
            new_name='created_at',
        ),
    ]
